import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [nombre, setNombre] = useState();
  useEffect(() => {
    // async function api(url) {
    //   const res = await fetch(url);
    //   return;
    //   res;
    // }
    // // fetch('./api/hello.js')
    // const apellido = api('http://localhost:3000/hello');
    // // setNombre(apellido);
    // console.log(apellido);
    const x = fetch('http://localhost:3000/api/hello').then((res) => {
      const respuesta = res.json();
      const h = respuesta.then((x) => {
        setNombre(x);
      });
    });
  }, []);

  // console.log(nombre);

  return (
    <div className={styles.container}>
      <Head>
        <title>ejercicio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='image-jeremy.png' />
      </Head>
      <body>
        <header>
          <div id='principal'>
            <img src='image-jeremy.png' />
            <div>
              <h2> Report for</h2>
              {nombre && <h1>{nombre.name}</h1>}
            </div>
          </div>
          <nav id='nav'>
            <button>Daily</button>
            <button>Weekly</button>
            <button>Monthly</button>
          </nav>
        </header>
        <main className={styles.main}>
          <section className='info' id='work'>
            <aside>
              <img src='icon-play.svg' />
            </aside>
            <article>
              <h1>Work</h1>
              <button className='abrir-cerrar'>...</button>
              <h2>5hrs</h2>
              <p>Previous - 7hrs</p>
            </article>
          </section>
          <section className='info' id='play'>
            <aside>
              <img src='icon-play.svg' />
            </aside>
            <article>
              <h1>Work</h1>
              <button>...</button>
              <h2>5hrs</h2>
              <p>Previous - 7hrs</p>
            </article>
          </section>
          <section className='info' id='study'>
            <aside>
              <img src='icon-play.svg' />
            </aside>
            <article>
              <h1>Work</h1>
              <button>...</button>
              <h2>5hrs</h2>
              <p>Previous - 7hrs</p>
            </article>
          </section>
          <section className='info' id='exercise'>
            <aside>
              <img src='icon-play.svg' />
            </aside>
            <article>
              <h1>Work</h1>
              <button>...</button>
              <h2>5hrs</h2>
              <p>Previous - 7hrs</p>
            </article>
          </section>
          <section className='info' id='social'>
            <aside>
              <img src='icon-play.svg' />
            </aside>
            <article>
              <h1>Work</h1>
              <button>...</button>
              <h2>5hrs</h2>
              <p>Previous - 7hrs</p>
            </article>
          </section>
          <section className='info' id='self-care'>
            <aside>
              <img src='icon-play.svg' />
            </aside>
            <article>
              <h1>Work</h1>
              <button>...</button>
              <h2>5hrs</h2>
              <p>Previous - 7hrs</p>
            </article>
          </section>
        </main>
      </body>
    </div>
  );
}
