import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { Info } from './components/Info';

export default function Home() {
  const [nombre, setNombre] = useState();
  const [activity, setActivity] = useState([]);
  const [time, setTime] = useState(null);
  const [daily, setDaily] = useState(true);
  const [weekly, setWeekly] = useState(false);
  const [monthly, setMonthly] = useState(false);

  useEffect(() => {
    const x = fetch('http://localhost:3000/api/hello').then((res) => {
      const respuesta = res.json();
      const h = respuesta.then((x) => {
        setNombre(x);
      });
    });
  }, []);

  useEffect(() => {
    const activity = fetch('../../api/db').then((res) => {
      const response = res.json();
      const respuesta = response.then((res) => {
        return setActivity(res.data);
      });
    });
  }, []);

  // activity && console.log(activity.length);

  // console.log('index', activity);

  return (
    <div className={styles.container} id='marco'>
      <Head>
        <title>ejercicio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='image-jeremy.png' />
      </Head>
      <body>
        <header>
          <div id='principal'>
            <img src='image-jeremy.png' />
            <div>
              <h2> Report for</h2>
              {nombre && <h1>{nombre.name}</h1>}
            </div>
          </div>
          <nav id='nav'>
            <button
              onClick={(e) => {
                setWeekly(false);
                setMonthly(false);
                setDaily(true);
              }}
            >
              Daily
            </button>
            <button
              onClick={(e) => {
                setWeekly(true);
                setMonthly(false);
                setDaily(false);
              }}
            >
              Weekly
            </button>
            <button
              onClick={(e) => {
                setWeekly(false);
                setMonthly(true);
                setDaily(false);
              }}
            >
              Monthly
            </button>
          </nav>
        </header>
        <main>
          {activity.length > 0 &&
            activity.map((act) => {
              return (
                <Info
                  id={act.title}
                  daily={daily}
                  weekly={weekly}
                  monthly={monthly}
                  time={act.timeframes}
                />
              );
            })}
        </main>
      </body>
    </div>
  );
}
